### PR TITLE
Feature/create bug

### LINKED ISSUE #166: Error when loading "Create Work" page
```
Showing /willow.development/app/views/records/edit_fields/_creator.html.erb where line #2 raised:

undefined method `first_name' for #<ActiveTriples::Resource:0x007f9dec03a098>
```

### PR DESCRIPTION
**Pull request by richard-jones**
Fixes #166

### CODE REVIEW

File: willow/app/inputs/nested_attributes_input.rb [hunk 1]
```diff
@@ -41,6 +48,9 @@ def build_field(value, index)
 
       @rendered_first_element = true
 
+      print "RICHARD SAYS"
```
Comment (anusharanganathan) [inline willow/app/inputs/nested_attributes_input.rb]: These need to be removed
